name = "Testmlbb"
main = "worker.js"
compatibility_date = "2025-08-10"

[vars]
SECRET_KEY = "3f5a1b2c4d6e7f8091a2b3c4d5e6f708"
WORKER_B_URL = "https://worker-b.domainkamu.workers.dev"

[[kv_namespaces]]
binding = "VALID_ACCOUNT"
id = "07dd21fac76a4178a37c28bad4b07ac1"
